### ISSUE TITLE
Question on callbacks

### ISSUE THREAD

**Issue by autodidaddict** [tessi/wasmex#256]
Sorry about doing this through the github, I wasn't sure how else to reach you.

I'm trying to implement something where Elixir has a pointer to my Rust struct and this rust struct can make callbacks up into Elixir (e.g. after it receives a gRPC message or a broker request, etc). This callback needs to be synchronous because it needs to potentially return a value.

I see you've got this implemented with the function imports, but I don't know how much of that I need to duplicate.

I'd like to be able to do something like:

`{:ok, whatevs} = MyModule.newGrpcThing(Module.For.Callbacks)`

and then I have callbacks that return values to answer the gRPC or message broker requests.

Do you have a blog post or some rustler documentation you used as a reference to implement this kind of callback functionality?

**Comment by tessi** [comment]
Hey @autodidaddict thanks for asking your question and please don't be sorry. If I can help bring Rust and Elixir closer together and help someone asking nice questions at the same time, it's a good day for me ;)

Let me get a disclaimer in before starting any actual explanation: There is currently a big refactoring ongoing in rustler. Wasmex still uses the pre-refactoring version (0.21) whereas the rustler repo/docs and many projects "in the wild" already reference the release candidate for 0.22. The refactoring features some bigger changes on usability/verbosity on the Rust-side. Thus, you'll find things being written a little different between wasmer and rustler docs at the moment.

Now to your scenario:

> I'm trying to implement something where Elixir has a pointer to my Rust struct and this rust struct can make callbacks up into Elixir (e.g. after it receives a gRPC message or a broker request, etc). This callback needs to be synchronous because it needs to potentially return a value.

I read this as a two step problem:

1. Hold a pointer to a Rust struct in elixir and call functions on it
2. Run elixir code (in a synchronous way) coming from Rust.

## Hold a pointer to a Rust struct in elixir and call functions on it

For step 1., it reads to me like you already achieved that so I try to keep it short. Feel happy to ask more questions, though. The trick is to use a [`ResourceArc`](https://docs.rs/rustler/0.22.0-rc.0/rustler/resource/struct.ResourceArc.html) in Rust and return that from a "make-the-struct" Rust-fn that can be called from Elixir. An example can be found in the rustler tests ([the Rust side](https://github.com/rusterlium/rustler/blob/6a63fc22b1c7d6a156bad31550df89063eab1cda/rustler_tests/native/rustler_test/src/test_resource.rs#L22) and also the [Elixir side](https://github.com/rusterlium/rustler/blob/6a63fc22b1c7d6a156bad31550df89063eab1cda/rustler_tests/test/resource_test.exs#L6)).

In wasmex, I have a similar setup: In [the Rust-part](https://github.com/tessi/wasmex/blob/ff5ae39604f4476fcf80b843cc5ef780788ea6f1/native/wasmex/src/instance.rs), there is a `new_from_bytes` function which instantiates a new WASM instance.

```rust
pub struct InstanceResource {
    pub instance: Mutex<Instance>,
}

pub fn new_from_bytes<'a>(env: RustlerEnv<'a>, args: &[Term<'a>]) -> Result<Term<'a>, Error> {
    // ...
    let instance = match Instance::new(&module, &import_object) {
        Ok(instance) => instance,
        Err(e) => return Ok((atoms::error(), format!("Cannot Instantiate: {:?}", e)).encode(env)),
    };
    // ...
    let resource = ResourceArc::new(InstanceResource {
        instance: Mutex::new(instance),
    });
    Ok((atoms::ok(), resource).encode(env))
}
```

which is called [in elixir](https://github.com/tessi/wasmex/blob/ff5ae39604f4476fcf80b843cc5ef780788ea6f1/lib/wasmex/instance.ex) like this:

```elixir
defmodule Wasmex.Instance do
  defstruct resource: nil,
            # The actual NIF instance resource.
            # Normally the compiler will happily do stuff like inlining the
            # resource in attributes. This will convert the resource into an
            # empty binary with no warning. This will make that harder to
            # accidentally do.
            # It also serves as a handy way to tell file handles apart.
            reference: nil

  def from_bytes(bytes, imports) when is_binary(bytes) and is_map(imports) do
    case Wasmex.Native.instance_new_from_bytes(bytes, imports) do
      {:ok, resource} -> {:ok, wrap_resource(resource)}
      {:error, err} -> {:error, err}
    end
  end

  defp wrap_resource(resource) do
    %__MODULE__{
      resource: resource,
      reference: make_ref()
    }
  end

  # ...
end
```

In Elixir, a Rust-struct resource looks like an empty binary (but it actually holds a reference to the struct, promised :)). This is called "resource object" in Erlang - you can read more on the topic [here](http://erlang.org/doc/man/erl_nif.html#resource_objects). 📖 

You can use that `resource` in Elixir as a normal param to be given to Rust:

```elixir
def function_export_exists(%__MODULE__{resource: resource}, name) when is_binary(name) do    
  Wasmex.Native.instance_function_export_exists(resource, name)
end
```

Where it can be used in Rust like this:

```rust
pub fn function_export_exists<'a>(env: RustlerEnv<'a>, args: &[Term<'a>]) -> Result<Term<'a>, Error> {
    let resource: ResourceArc<InstanceResource> = args[0].decode()?;
    let function_name: String = args[1].decode()?;
    let instance = resource.instance.lock().unwrap();

    Ok(functions::exists(&instance, &function_name).encode(env))
}
```

## Run elixir code (in a synchronous way) coming from Rust.

Calling from a NIF (e.g. Rust) into Elixir is not meant to be possible in a synchronous way. The only thing that Erlang allows NIFs to do is doing message sends (via [`enif_send`](http://erlang.org/doc/man/erl_nif.html#enif_send)) which is an **asynchronous** call into an Erlang process (e.g. `GenServer` in Elixir).

I invented a trick combining multi-threading and uniquely created token resources which we can wait for. Let me explain:

1. My Rust-code that executes WASM functions [runs in a separate thread](https://github.com/tessi/wasmex/blob/ff5ae39604f4476fcf80b843cc5ef780788ea6f1/native/wasmex/src/instance.rs#L80) than the main NIF thread elixir calls into.
2. When doing the asynchronous call to Elixir (from that thread), we also pass a unique token along with the function name and params. Then we put the thread to sleep.
3. Once Elixir finishes the function execution, it calls back into the Rust NIF providing the unique token and a result (or error).
4. In the NIF's main thread, we extract the result and signal the sleeping thread to continue with the use of our unique token

Since we put the worker-thread to sleep while elixir executes and only wake it when a result comes back, the thread "thinks" the execution was synchronous. This approach has some downsides - e.g. no one guarantees that Elixir will actually call back ([but who could even do such a promise anyways?](https://en.wikipedia.org/wiki/Halting_problem)). All in all, this approach  turns out to work really, really well for my uses.

Let's go into the code that makes this happen. The "unique token" is the magic sauce, that is just another Rust struct that can be passed to Elixir as a "resource object".

```Rust
pub struct CallbackTokenResource {
    pub token: CallbackToken,
}

pub struct CallbackToken {
    pub continue_signal: Condvar,
    pub return_values: Mutex<Option<(bool, Vec<WasmValue>)>>,
    // ...
}
```
<sub>source code [here](https://github.com/tessi/wasmex/blob/ff5ae39604f4476fcf80b843cc5ef780788ea6f1/native/wasmex/src/environment.rs#L25)</sub>

It's main feature is the `continue_signal` [`Condvar`](https://doc.rust-lang.org/std/sync/struct.Condvar.html). Let me cite the rust docs here, as I can't explain `CondVars` better:

> Condition variables represent the ability to block a thread such that it consumes no CPU time while waiting for an event to occur. Condition variables are typically associated with a boolean predicate (a condition) and a mutex. The predicate is always verified inside of the mutex before determining that a thread must block.
>
> Functions in this module will block the current thread of execution.

Using this `CondVar`, we can put the worker thread to sleep after calling into Elixir. We also use the token to "transfer" the elxir-function-call results between our Rust threads.

A sequence diagram nicely features the actual methods being called in wasmex:

<img width="971" alt="sequence diagram visualizing the aforementioned process" src="https://user-images.githubusercontent.com/206108/119581276-88b80b00-bdc2-11eb-8378-3666cdb9f100.png">

I spare you citations of the code in this answer, but here are links to implementations of the mentioned methods for further study:

* [`function imports just before calling into Elixir` (Rust)](https://github.com/tessi/wasmex/blob/ff5ae39604f4476fcf80b843cc5ef780788ea6f1/native/wasmex/src/environment.rs#L165)
* [the `iinvoke_callback` handler in our GenServer (Elixir)](https://github.com/tessi/wasmex/blob/ff5ae39604f4476fcf80b843cc5ef780788ea6f1/lib/wasmex.ex#L166)
* [`receive_callback_result` (Rust)](https://github.com/tessi/wasmex/blob/ff5ae39604f4476fcf80b843cc5ef780788ea6f1/native/wasmex/src/namespace.rs#L16)

## Meta

I hope this monologue was long enough to shine some light and help you, but short enough to not make you fall asleep or leave you puzzled. Please follow up with any questions, should something be unclear.

As you asked for a reference to a blog post -- I didn't write these thoughts down yes (expect here and the original PR). I consider blogging this, but would be interested in your feedback. Is the explanation above good enough for a general audience (knowledgeable in Elixir)? What are you missing? What can be done better?

cheers,
tessi 👋

**Comment by autodidaddict** [comment]
This is amazing. I'm working on a few other pieces of my code that don't get into callbacks, but I think tomorrow morning I'll be about ready to start working with them. Thanks so much for all this detailed information! I'll let you know some more feedback on it re: blob posting as I go through the information tomorrow.

**Comment by tessi** [comment]
For further reference, there is an elixirforum discussion mentioning this topic: https://elixirforum.com/t/calling-elixir-in-rust/40121/6

And a relatively old erlang discussion featuring a similar approach to mine: https://erlang.org/pipermail/erlang-questions/2018-January/094626.html
