### ISSUE TITLE
Example using WASI

### ISSUE THREAD

**Issue by munjalpatel** [tessi/wasmex#362]
This is a great project and awesome work @tessi !

Are there any examples I can take a look at that involves WASI?
Specifically, I am looking to make HTTP requests and use the filesystem from within the WASM.

Thank you!

**Comment by tessi** [comment]
Hey @munjalpatel 👋 

thanks and great question! I guess we need to improve our docs in that regard.

There are many examples in our [`wasi_tests`](https://github.com/tessi/wasmex/blob/main/test/wasi_test.exs). They include "preopens" of host directories (so that WASI executables can access the host file system). Beware, that file access permissions are likely to be removed or changed in our next major version.

You may also find some hints in our [changelog](https://github.com/tessi/wasmex/blob/main/CHANGELOG.md#added-4) which contains my favourite WASI example :)

```elixir
# after a `wapm install cowsay`
{:ok, bytes } = File.read("wapm_packages/_/cowsay@0.2.0/target/wasm32-wasi/release/cowsay.wasm")
{:ok, stdout} = Wasmex.Pipe.create()
{:ok, stdin} = Wasmex.Pipe.create()
{:ok, instance } = Wasmex.start_link(%{bytes: bytes, wasi: %{stdout: stdout, stdin: stdin}})
Wasmex.Pipe.write(stdin, "Why do you never see elephants hiding in trees? Because they're really good at it.")
{:ok, _} = Wasmex.call_function(instance, :_start, [])
IO.puts Wasmex.Pipe.read(stdout)
  ________________________________________
/ Why do you never see elephants hiding  \
| in trees? Because they're really good  |
\ at it.                                 /
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
               ||----w |
                ||     ||
:ok
```

Our [official docs](https://hexdocs.pm/wasmex/Wasmex.html#start_link/1-wasi) may help too. If you find something missing or hard to understand in our docs, I'd be happy for feedback or PRs fixing things :)

Does that help?

**Comment by munjalpatel** [comment]
Hey @tessi , thanks a lot, this is very helpful. I was able to understand this reading through the code :)
